spring:
  application:
    name: zemnnni


mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true


option:
  security:
    filter:
      sign-in-filter:
        enabled : true
        url : /sign-in
    sign-in:
      try-count:
        limit: 5